---
name: stratis-cli CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - develop-2.3.0
  pull_request:
    branches:
      - master
      - develop-2.3.0

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  python-checks:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # MANDATORY CHECKS USING CURRENT DEVELOPMENT INTERPRETER
          - python-version: 3.9.2
            dependencies: >
              pylint==2.6.0
              dbus-client-gen==0.4
              dbus-python-client-gen==0.7
              justbytes==0.11
              python-dateutil==2.8.1
              wcwidth==0.2.5
              psutil==5.7.2
              semantic_version==2.8.4
            task: PYTHONPATH=./src make -f Makefile lint
          - python-version: 3.9.2
            dependencies: black==20.8b1 isort==5.6.4
            task: make -f Makefile fmt-travis
          - python-version: 3.9.2
            dependencies: >
              dbus-client-gen==0.4
              dbus-python-client-gen==0.7
              justbytes==0.11
              python-dateutil==2.8.1
              wcwidth==0.2.5
              psutil==5.7.2
              semantic_version==2.8.4
            task: PYTHONPATH=./src make -f Makefile test-travis
          # MANDATORY CHECKS USING LOWEST SUPPORTED INTERPRETER
          - python-version: 3.6.8
            dependencies: >
              pylint==2.4.4
              dbus-client-gen==0.4
              dbus-python-client-gen==0.7
              justbytes==0.11
              python-dateutil==2.6.1
              psutil==5.4.3
              semantic_version==2.6.0
            task: PYTHONPATH=./src make -f Makefile lint
          # VERIFICATION OF TEST INFRASTRUCTURE
          - python-version: 3.9.2
            dependencies: yamllint==1.26.0
            task: make -f Makefile yamllint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libdbus-glib-1-dev
          pip3 install ${{ matrix.dependencies }}
      - name: Run test
        run: ${{ matrix.task }}
